version: '3.8'
services:
  app:
    image: work-competition
    environment:
      - NEXT_PUBLIC_BASE_URL
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "8080:8080"