version: '3.8'
services:
  app:
    image: work-competition
    environment:
      NEXT_PUBLIC_BASE_URL: "https://best-image-competition-bc327bfa5fa3.herokuapp.com"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "8080:8080"