import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";

import "@/styles/globals.css";

const nunitoSans = Nunito_Sans({ subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>{children}</body>
    </html>
  );
}
