export enum Pages {
  inovativeSolutions = 'inovative-solutions',
  bestSpecialist = 'best-specialist',
  effectiveSupport = 'effective-support',
  art = 'art',
  postersAndInformation = 'posters-and-information',
  photosAndCollages = 'photos-and-collages',
  drawings = 'drawings',
  videos = 'videos',
}

export enum ErrorMessages {
  Required = "є обов'язковим",
  EmailInvalid = "Невірний формат електронної пошти",
  PhoneInvalid = "Номер телефону невірний",
  RegionInvalid = "Неправильний формат області. Введіть: Львівська, Київська і т.д",
  FileSize = "Розмір файлу перевищує 50 МБ",
  FileType = "Не валідний формат файлу",
  FileRequired = "Файл є обов'язковим",
  PageNotFound = "Сторінку не знайдено",
  ConsentRequired = "Ви повинні надати згоду на обробку персональних даних.",
  BirthDateInvalid = "Рік народження має містити 4 числа",
}

export enum Regions {
  Lviv = 'Львівська',
  Kyiv = 'Київська',
  Kharkiv = 'Харківська',
  Dnipro = 'Дніпропетровська',
  Odesa = 'Одеська',
  Zaporizhzhia = 'Запорізька',
  Chernivtsi = 'Чернівецька',
  IvanoFrankivsk = 'Івано-Франківська',
  Ternopil = 'Тернопільська',
  Vinnytsia = 'Вінницька',
  Khmelnytskyi = 'Хмельницька',
  Rivne = 'Рівненська',
  Zakarpattia = 'Закарпатська',
  Poltava = 'Полтавська',
  Sumy = 'Сумська',
  Kherson = 'Херсонська',
  Zhytomyr = 'Житомирська',
  Cherkasy = 'Черкаська',
  Luhansk = 'Луганська',
  Donetsk = 'Донецька',
  Mykolaiv = 'Миколаївська',
  Volyn = 'Волинська',
  Kirovohrad = 'Кіровоградська',
  Chernihiv = 'Чернігівська',
  Crimea = 'АР Крим',
}
